export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_DISCOUNT = 'ADD_DISCOUNT';
export const GET_DISCOUNTS = 'GET_DISCOUNT';
export const UPDATE_DISCOUNT = 'UPDATE_DISCOUNT';
export const DELETE_DISCOUNT = 'DELETE_DISCOUNT';

export const EDIT_DISCOUNT_DATA = 'EDIT_DISCOUNT_DATA';
export const LOADING = 'LOADING';
export const USER_DEAL_LOADING = 'USER_DEAL_LOADING';
export const GET_USER_DISCOUNT = 'GET_USER_DISCOUNT';
export const SET_USERS_SELECTION = 'SET_USERS_SELECTION';
export const SAVE_USER_DISCOUNT = 'SAVE_USER_DISCOUNT';
export const SET_TOTAL_LOCK_PRICE = 'SET_TOTAL_LOCK_PRICE';
export const CONFIRM_PAYMENT = 'CONFIRM_PAYMENT';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';

export const EDIT_LOCKED_OFFER = 'EDIT_LOCKED_OFFER';
export const DELETE_LOCKED_OFFER = 'DELETE_LOCKED_OFFER';
export const LOCKED_OFFER_LOADING = 'LOCKED_OFFER_LOADING';
export const GET_LOCKED_OFFERS = 'GET_LOCKED_PRICE';
export const SET_EDIT_DATA = 'SET_EDIT_DATA';

export const SEARCH_DISCOUNT = 'SEARCH_DEAL';
